name: golangci-lint
on:
  push:
    tags:
      - v2*
    branches:
      - master
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    strategy:
      fail-fast: false
      matrix:
        go-version: [
                # 1.19.x, # Ended 06 Sep 2023
                # 1.20.x, # Ended 06 Feb 2024
                1.21.x,
                1.22.x,
                ]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          # version: v1.29
          version: v1.55

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --timeout 2m

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
